### ISSUE TITLE
Gatsby V3

### ISSUE THREAD

**Issue by muuvmuuv** [me4502/gatsby-plugin-react-helmet-async#57]
Gatsby released version 3 recently. It now prints this warning. I could not test if this plugin still works since I am doing a huge rewrite of my project but maybe someone else can.

```
warn Plugin gatsby-plugin-react-helmet-async is not compatible with your gatsby version 3.0.0 - It requires gatsby@2.x
```

**Comment by kimbaudi** [comment]
the reason you see this warning is because you upgraded to Gatsby v3 while this package has a peer dependency on gatsby v2 (see https://github.com/Collabsalot/gatsby-plugin-react-helmet-async/blob/master/package.json#L48)

this package just uses the `HelmetProvider` context provider from 'react-helmet-async' and injects it into gatsby's `wrapRootElement` (see https://github.com/Collabsalot/gatsby-plugin-react-helmet-async/blob/master/src/gatsby-browser.tsx).  it also handles SSR by injecting `HelmetData` context (see https://github.com/Collabsalot/gatsby-plugin-react-helmet-async/blob/master/src/gatsby-ssr.tsx).

You could simply ignore the warning. When the plugin author updates peer dependency on Gatsby from v2 to v3, you will no longer see the warning.

Or you could choose not to install this plugin and just edit `gatsby-browser.js` and/or `gatsby-ssr.js` to inject `<HelmetProvider>` from `react-helmet-async` yourself and remove this extra dependency.

**Comment by MartinRosenberg** [comment]
@kimbaudi is right on all counts, including that you could just add these things to your own `gatsby-browser.js` and `gatsby-ssr.js` - I won't be offended at all.

That said, if you do want to use this, I just corrected the peer dependencies in v1.2.0 (14c781d) to include Gatsby 3 and React 17. Gatsby's migration guide doesn't indicate any changes related to this, so it should work exactly the same as before.

**Comment by JohnRDOrazio** [comment]
How about Gatsby 4? 😄

**Comment by MartinRosenberg** [comment]
How are they already on 4?! I'll look into it 😅
